config/routes.rb
Rails.application.routes.draw do
  get 'articles', to: 'articles#index'
  get 'articles/new', to: 'articles#new'

  get 'article/:id/edit', to: 'articles#edit', as: :edit
  get 'article/:id', to: 'articles#show', as: :article

  delete 'article/:id', to: 'articles#destroy'
  patch 'article/:id', to: 'articles#update'
  post 'articles', to: 'articles#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to article_path(@article)
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to articles_path
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require('article').permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<div class="container">
  <h1>Edit exisisting Article</h1>

  <div style="width: 400px">
    <%= form_for(@article) do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      <%= f.submit class: 'btn btn-primary' %>
      <%end%>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container" >
  <h1>All Articles</h1>
  <p>Browse through the library:</p>
  <ol>
  <% @articles.each do |article|%>
    <li> Title: <%=link_to article.title, article_path(article)%>
    <%= link_to ' [ Delete ]', article_path(article),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
    </li>
  <% end %>
  </ol>

  <button type="button" class="btn btn-outline-primary"><%=link_to 'Add Article', articles_new_path%></button>
</div>

app/views/articles/new.html.erb
<div class="container">
  <h1>Create new Article</h1>

  <div style="width: 400px">
    <%= form_for(@article) do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      <%= f.submit class: 'btn btn-primary' %>
      <%end%>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="header_link">
    <h1><%=@article.title%> </h1>
    <button type="button" class="btn btn-outline-primary"><%=link_to 'Edit Article', edit_path(@article)%></button>
  </div>
  <p><%=@article.content%></p>

  <%=link_to 'Back to overview', articles_path%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>

  <body>
    <%= yield %>
  </body>
</html>